---
apiVersion: v1
kind: Pod
metadata:
  name: utils
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  - name: sampleconfig
    hostPath:
      path: /tmp/sampleconfig
  containers:
  - name: cryptogen
    image: hyperledger/fabric-tools:1.2.0
    imagePullPolicy: Always
    command: ["sh", "-c", "cryptogen generate --config /tmp/sampleconfig/crypto-config.yaml && cp -r crypto-config /shared/ && for file in $(find /shared/ -iname *_sk); do dir=$(dirname $file); mv ${dir}/*_sk ${dir}/key.pem; done && find /shared -type d | xargs chmod a+rx && find /shared -type f | xargs chmod a+r && touch /shared/status_cryptogen_complete "]
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /tmp/sampleconfig
      name: sampleconfig
  - name: configtxgen
    image: hyperledger/fabric-tools:1.2.0
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 1 && while [ ! -f /shared/status_cryptogen_complete ]; do echo Waiting for cryptogen; sleep 1; done; cp /tmp/sampleconfig/configtx.yaml /shared/configtx.yaml; cd /shared/; configtxgen -profile OneOrgsOrdererGenesis -outputBlock orderer.block && find /shared -type d | xargs chmod a+rx && find /shared -type f | xargs chmod a+r && touch /shared/status_configtxgen_complete && rm /shared/status_cryptogen_complete"]
    env:
     - name: PEERHOST1
       value: blockchain-org1peer1
     - name: PEERPORT1
       value: "30110"
     - name: ORDERER_URL
       value: blockchain-orderer:31010
     - name: FABRIC_CFG_PATH
       value: /shared
    # - name: GODEBUG
    #   value: "netdns=go"
     - name: HTTP_PROXY
       value: "http://proxy.egat.co.th:8080"
     - name: HTTPS_PROXY
       value: "http://proxy.egat.co.th:8080"
     - name: NO_PROXY
       value: "10.205.51.76,mycluster.icp,mongodb,platform-identity-provider,platform-identity-management,icp-management-ingress,localhost,127.0.0.1,10.205.51.0/24,10.1.0.0/16,10.0.0.1/24"
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /tmp/sampleconfig
      name: sampleconfig
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-orderer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer
    spec:
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc

      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:1.2.0
        command: ["sh", "-c", "orderer"]
        env:
        - name: ORDERER_CFG_PATH
          value: /shared/
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /mnt/ledger/orderer1
        - name: ORDERER_GENERAL_BATCHTIMEOUT
          value: 1s
        - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
          value: "10"
        - name: ORDERER_GENERAL_MAXWINDOWSIZE
          value: "1000"
        - name: ORDERER_GENERAL_ORDERERTYPE
          value: solo
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "31010"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /shared/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /shared/orderer.block
        - name: ORDERER_GENERAL_GENESISPROFILE
          value: initial
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: GODEBUG
          value: "netdns=go"
        - name: HTTP_PROXY
          value: "http://proxy.egat.co.th:8080"
        - name: HTTPS_PROXY
          value: "http://proxy.egat.co.th:8080"
        - name: NO_PROXY
          value: "10.205.51.76,mycluster.icp,mongodb,platform-identity-provider,platform-identity-management,icp-management-ingress,localhost,127.0.0.1,10.205.51.0/24,10.1.0.0/16,10.0.0.1/24"
        volumeMounts:
        - mountPath: /shared
          name: shared

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ca
    spec:
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc

      containers:
      - name: ca
        image: hyperledger/fabric-ca:1.2.0
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw"]
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: CONFIGYAML
          value: /shared/cas/ca.yaml
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca.example.com
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: /shared/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: /shared/crypto-config/peerOrganizations/org1.example.com/ca/key.pem
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /etc/hyperledger/fabric-ca-server/ca-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /etc/hyperledger/fabric-ca-server/ca-key.pem
        - name: GODEBUG
          value: "netdns=go"
        - name: HTTP_PROXY
          value: "http://proxy.egat.co.th:8080"
        - name: HTTPS_PROXY
          value: "http://proxy.egat.co.th:8080"
        - name: NO_PROXY
          value: "10.205.51.76,mycluster.icp,mongodb,platform-identity-provider,platform-identity-management,icp-management-ingress,localhost,127.0.0.1,10.205.51.0/24,10.1.0.0/16,10.0.0.1/24"
        volumeMounts:
        - mountPath: /shared
          name: shared

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-org1peer1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: org1peer1
    spec:
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: org1peer1
        image: hyperledger/fabric-peer:1.2.0
        command: ["sh", "-c", "peer node start"]
        env:
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org1peer1
        - name: CORE_PEER_ADDRESS
          value: blockchain-org1peer1:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: blockchain-org1peer1:30110
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_LOGGING_CAUTHDSL
          value: debug
        - name: CORE_LOGGING_GOSSIP
          value: debug
        - name: CORE_LOGGING_LEDGER
          value: debug
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: debug
        - name: CORE_LOGGING_GRPC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: goleveldb
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: blockchain-orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: NO_PROXY
          value: "10.205.51.76,mycluster.icp,mongodb,platform-identity-provider,platform-identity-management,icp-management-ingress,localhost,127.0.0.1,10.205.51.0/24,10.1.0.0/16,10.0.0.1/24"
        volumeMounts:
        - mountPath: /shared
          name: shared
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
